CREATE DATABASE GROUP4 CHARACTER SET UTF8;
USE GROUP4;

CREATE TABLE USER_INFO
(
ID INT NOT NULL AUTO_INCREMENT,
Name CHAR(32) NOT NULL,
Email CHAR(64) NOT NULL,
Pwd   CHAR(32) NOT NULL,
Info  NVARCHAR(140) NOT NULL DEFAULT "该用户比较懒，什么都没有留下。",
Avatar  VARCHAR(64) NOT NULL,
Status  INT NOT NULL DEFAULT 1,
PRIMARY KEY (ID)
);

CREATE TABLE VOTE_INFO
(
ID INT NOT NULL AUTO_INCREMENT,
OwnerID INT NOT NULL,
Title NVARCHAR(100) NOT NULL,
CreateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
DueTime TIMESTAMP NOT NULL,
Status INT NOT NULL DEFAULT 1,
DescInfo NVARCHAR(140) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (OwnerID) REFERENCES USER_INFO(ID)
);

CREATE TABLE VOTE_OPTION
(
ID INT NOT NULL AUTO_INCREMENT,
VoteID INT NOT NULL,
Title NVARCHAR(100) NOT NULL,
Image VARCHAR(64) NOT NULL,
DescInfo NVARCHAR(140) NOT NULL,
Support INT NOT NULL DEFAULT 0,
PRIMARY KEY (ID),
FOREIGN KEY (VoteID) REFERENCES VOTE_INFO(ID)
);

CREATE TABLE VOTE_RECORD
(
VoteID INT NOT NULL,
UserID INT NOT NULL,
OptionID INT NOT NULL,
CreateTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
Comment NVARCHAR(140) DEFAULT NULL,
PRIMARY KEY (UserID, VoteID),
FOREIGN KEY (VoteID) REFERENCES VOTE_INFO(ID),
FOREIGN KEY (UserID) REFERENCES USER_INFO(ID),
FOREIGN KEY (OptionID) REFERENCES VOTE_OPTION(ID)
);

CREATE TABLE VOTE_FOLLOW
(
UserID INT NOT NULL,
VoteID INT NOT NULL,
PRIMARY KEY (UserID, VoteID),
FOREIGN KEY (UserID) REFERENCES USER_INFO(ID),
FOREIGN KEY (VoteID) REFERENCES VOTE_INFO(ID)
);

CREATE TABLE ADMIN_INFO
(
ID INT NOT NULL AUTO_INCREMENT,
Name CHAR(32) NOT NULL,
Password CHAR(32) NOT NULL,
PRIMARY KEY (ID)
)